# Generated by Django 3.2.12 on 2025-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('paper_type', models.CharField(max_length=50)),
                ('year_exam', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='exam_papers/')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
